spring.application.name=zorvyn-backend-assignment
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/zorvyn_database
spring.datasource.username=root
spring.datasource.password=Vansh@13

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

basePath=/api/v1

# JWT Configuration
jwt.secret=Z29ydnluLWJhY2tlbmQtYXNzaWdubWVudC1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1lbm91Z2gtZm9yLUhTMjU2
jwt.expiration=86400000

# GraphQL Configuration
spring.graphql.http.path=${basePath}/dashboard